# Project Properties
mod_version = 1.0.10
maven_group = dev.swiftclient
archives_base_name = swiftclient-mod

# Dependencies
minecraft_version = 26.2
loader_version = 0.19.5
fabric_version = 0.115.0+26.2

# Loom configuration
loom.platform = fabric
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
